### ISSUE TITLE
The image tiles are being served in the demo

### ISSUE THREAD

**Issue by frowenz** [agrbin/fractal-mosaic#1]
I am very interested in seeing this project in action. Is there any way to run it locally?

**Comment by agrbin** [comment]
Thank you for the question!

I spent some time today to try to re-run it on a different backend server. The demo link is the same as before: https://agrbin.github.io/fractal-mosaic/

During this I learned how troublesome is to run this e2e locally (no docker support was built). Another issue is that it requires a big data file with images that I ressurected from some backups.

Needless to say, this project is not under active development -- it was just a demo for fun.
